### ISSUE TITLE
`lsp-volar--activate-p` unconditionally enables volar on projects that have a vite config

### ISSUE THREAD

**Issue by ohmree** [jadestrong/lsp-volar#1]
See title, the project was generated by doing `pnpm create vite` and choosing vanilla-ts.

With the `create-vite` generated project I also got [this `f-join` error](https://github.com/emacs-lsp/lsp-mode/issues/3261), the cause of which I was able to find using `doom-debug-mode`.
On another project it didn't seem like I was getting this error, so I didn't think about looking at the stack trace but I have confirmed that when I add the vite config  `(lsp-volar--activate-p "main.ts")` returns non-nil, and nil when I remove it.

I'm using doom emacs and have installed this package according to the doom-specific instructions in the readme.

Sorry if this counts as a duplicate, I just thought I'd share an observation I had when running into issues that weren't necessarily the `volarrc`-related error mentioned earlier.

EDIT: trying to find a fix for this (that isn't removing the `volar-server` binary from my system) I came up with this:
```elisp
;; $DOOMDIR/config.el
(after! lsp-javascript
  (set-lsp-priority! 'ts-ls 2))
```
It doesn't completely prevent volar from running in non-vue projects but it replaces one of its processes with `ts-ls` which at least works correctly for regular typescript code, with the minor annoyance that there's a constant loading bar in the bottom right corner (which I'm assuming is because the volar startup process is getting nowhere without an actual vue file).

If anyone knows of a better hack until this gets fixed I'd love to know about it.

EDIT 2:
Setting `lsp-volar-take-over-mode` to `nil` seems to work better than the hack in my first edit (assuming the user is fine with [the performance implications described here](https://github.com/johnsoncodehk/volar/discussions/471)).

**Comment by jadestrong** [comment]
I have add `(and (lsp-workspace-root) ...)` add fix the error. You can update `lsp-volar` to try again.

I didn't consider non Vue projects before, so I forced the vite project to be identified as a Vue project. Maybe I need to find a more reliable way to define whether the current project is a Vue project, so as to make Take Over Mode to work.

**Comment by jadestrong** [comment]
Now I add a method `lsp-volar-vite-vue-project-p` to check is `package.json` file has a `vue` package as dependencies.

**Comment by RKBK** [comment]
@jadestrong Thanks for your work on lsp for volar! It's something I use daily, and I really appreciate your effort to support it.

Does the fix you added mean that the related issue in lsp-mode, https://github.com/emacs-lsp/lsp-mode/issues/3261 , can be fixed? I think it would be great if lsp-volar could be added to the main lsp-mode repository!

**Comment by jadestrong** [comment]
@RKBK Yes，there should be some small optimization points at present. When it is completed, I will add it to lsp-mode.
