### ISSUE TITLE
Project create with Vue CLI does not start LS

### ISSUE THREAD

**Issue by ohhskar** [jadestrong/lsp-volar#3]
A project that was created with Vue CLI does not start the Language Server. Volar is not included as available servers to be used, even if the filetype is `.vue`.

These are the available language servers that lsp-mode offers when opening a file:
![image](https://user-images.githubusercontent.com/15758219/150776656-3aa241bb-a2bd-4350-b86d-9d0fc5fe0de1.png)

This issue is not present when the [volar-start](https://github.com/johnsoncodehk/volar-starter) project is used.

I've checked/tried the following:
- `vue` is included in the package.json dependencies
- `.volarrc` is added to the root of the project

**Comment by jadestrong** [comment]
What's the output when you type this command in your project:
```
M-x eval-expression
(lsp-volar--activate-p (buffer-file-name))
```

**Comment by dirodriguezm** [comment]
The same thing happened to me and the output from 

```
M-x eval-expression
(lsp-volar--activate-p (buffer-file-name))
```
Is `nil`.
