### ISSUE TITLE
[QA] multiple features

### ISSUE THREAD

**Issue by noor-tg** [jadestrong/lsp-volar#4]
does lsp volar support: 
- import component to script block when write name in template section ? (as lsp code action)
- what about eslint check component use in template section when import in script setup section ?
- does this mode work with web-mode ?

thank you

**Comment by jadestrong** [comment]
![output-2022-03-25-17:23:26](https://user-images.githubusercontent.com/18475217/160093079-5ea728dd-9544-4076-bb20-9112492c9ca8.gif)

Yes. Its basic behavior is consistent with vscode. And I use doom-emacs, it use `web-mode` as the major mode of the vue file.

**Comment by noor-tg** [comment]
any custom config to handle this ?

**Comment by noor-tg** [comment]
I use the following as my config for `vue` `web-mode` `lsp`
```elisp
;; config.el
(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))

(use-package! lsp-volar
  :init
  (setq lsp-volar-add-on-mode t))

(add-hook 'web-mode-hook 'prettier-js-mode)

;; lsp
(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 1024 1024)) ;; 1m(setq gc-cons-threshold 100000000)
(setq lsp-idle-delay 0.200)
(setq lsp-ui-doc-use-webkit t)

;; packages.el
(package! lsp-volar :recipe (:host github :repo "jadestrong/lsp-volar"))

;; init.el
(javascript +lsp)
(web +lsp)

```

**Comment by jadestrong** [comment]
If you use doom-emacs,  you can remove `(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))` the line. And just add this line `(use-package! lsp-volar)` in `config.el`. No need `setq lsp-volar-add-on-mode`

**Comment by jadestrong** [comment]
Did you enable  `:tools lsp` in `init.el` ?

**Comment by noor-tg** [comment]
> Did you enable `:tools lsp` in `init.el` ?

yes

**Comment by noor-tg** [comment]
> If you use doom-emacs, you can remove `(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))` the line. And just add this line `(use-package! lsp-volar)` in `config.el`. No need `setq lsp-volar-add-on-mode`

what if I use it with some other lsp like `lsp-tailwindcss` ?

**Comment by jadestrong** [comment]
After configuration, execute `M-x lsp-install-server` and select `volar-api` to install the server.

**Comment by noor-tg** [comment]
does it support component props autocomplete and type check ?

**Comment by jadestrong** [comment]
> does it support component props autocomplete and type check ?

Yes.

**Comment by jadestrong** [comment]
It doesn't conflict with `lsp-tailwindcss` . Just configure it. I haven't used tailwindcss, I'm not sure if `volar` supports it.

**Comment by noor-tg** [comment]
I use doom emacs. but I do not see this 
```
setup sugar [x] | ref sugar [ ]
```
can you share your config about web, js, vue, lsp, typescript, eslint ?
to know if I miss some thing . or to learn more about emacs configs.

**Comment by noor-tg** [comment]
> It doesn't conflict with `lsp-tailwindcss` . Just configure it. I haven't used tailwindcss, I'm not sure if `volar` supports it.

lsp-tailwindcss only autocomplete class names in 2 places inside class attribute , and inside style section.

**Comment by jadestrong** [comment]
Here is my config https://github.com/jadestrong/dotfiles/tree/master/home/.doom.d 

In the vue file, the `lsp-tailwindcss` cannot work and only rely on `vue-language-server`.

**Comment by jadestrong** [comment]
https://github.com/johnsoncodehk/volar-starter
You can test it in this project.

**Comment by noor-tg** [comment]
> ![output-2022-03-25-17:23:26](https://user-images.githubusercontent.com/18475217/160093079-5ea728dd-9544-4076-bb20-9112492c9ca8.gif)
> 
> Yes. Its basic behavior is consistent with vscode. And I use doom-emacs, it use `web-mode` as the major mode of the vue file.

when I try to import component after write  component name in template block or when do `lsp code action` on it. nothing happen.

**Comment by noor-tg** [comment]
and components names autocomplete is not showing too.
can this be related to my project setup not emacs config ?

**Comment by jadestrong** [comment]
![image](https://user-images.githubusercontent.com/18475217/160100620-508cc773-0aa8-4f2f-8f55-62e4c15a97d4.png)
Did you enable `:completion company` ?

**Comment by jadestrong** [comment]
When you open a vue file,

**Comment by jadestrong** [comment]
![image](https://user-images.githubusercontent.com/18475217/160100938-74eca635-e967-4bd1-b938-511ae0ab114a.png)
Did you see this message when you open a vue file.

**Comment by noor-tg** [comment]
> Here is my config https://github.com/jadestrong/dotfiles/tree/master/home/.doom.d
> 
> In the vue file, the `lsp-tailwindcss` cannot work and only rely on `vue-language-server`.

thank you. I will check it out.

**Comment by noor-tg** [comment]
> ![image](https://user-images.githubusercontent.com/18475217/160100938-74eca635-e967-4bd1-b938-511ae0ab114a.png) Did you see this message when you open a vue file.

yes

**Comment by noor-tg** [comment]
> ![image](https://user-images.githubusercontent.com/18475217/160100620-508cc773-0aa8-4f2f-8f55-62e4c15a97d4.png) Did you enable `:completion company` ?

yes but without this `+childframe` option

**Comment by jadestrong** [comment]
> > ![image](https://user-images.githubusercontent.com/18475217/160100620-508cc773-0aa8-4f2f-8f55-62e4c15a97d4.png) Did you enable `:completion company` ?
> 
> yes but without this `+childframe` option

It doesn't matter.

**Comment by jadestrong** [comment]
Is there autocomplete in js or ts file?

**Comment by jadestrong** [comment]
Maybe you should open a common js file, see if the company + lsp works.

**Comment by noor-tg** [comment]
> Maybe you should open a common js file, see if the company + lsp works.

- I upgraded doom emacs to latest update.
I think lsp + company is not working in my config.

**Comment by noor-tg** [comment]
even in ts files

**Comment by noor-tg** [comment]
I will check my configs to fix lsp + company first.

if the problem presist with vue files . I will reply here again.

thank you.

**Comment by jadestrong** [comment]
Generally speaking, you don't need to make other configurations, just in `init.el`, and then install some related dependencies. For example, `typescript-language-server 、typescript、vls、eslint and so on`, then it can work in a general JS project or Vue project (if you installed `vls`). If everything is normal, you can configure `volar` again.
You can do all this through `M-x lsp-install-server` .

In addition, I have submitted the project to `lsp-mode`. If `doom-emacs` upgraded `lsp-mode`,there is no need to configure `lsp-volar` separately.
Similarly, you can confirm througn `lsp-install-server`.

**Comment by noor-tg** [comment]
hey @jadestrong . thank you for your advice.
multiple notes:
- my previous doom version (before the QA) was not updated before 10 weeks ago.
- after my discussion with you I updated it and removed multiple configs related to lsp
- then vue local component auto complete worked.
- errors in templates about props shows but there not good auto complete for them
- company + lsp is working but it is slow
- there is problem with third party modules (components) like (@mdi/js) or (vue3-material-design-icons-ts) packages there is no auto complete for them (even they have ts types).

this is my xp after my last comment about the package and using it with doom emacs.

my questions are :
- **how to allow autocomplete for components in node_modules ?**
- **how to make lsp + company  faster when writing vue code ?**

thank you in advance.

**Comment by noor-tg** [comment]
> Generally speaking, you don't need to make other configurations, just in `init.el`, and then install some related dependencies. For example, `typescript-language-server 、typescript、vls、eslint and so on`, then it can work in a general JS project or Vue project (if you installed `vls`). If everything is normal, you can configure `volar` again. You can do all this through `M-x lsp-install-server` .
> 
> In addition, I have submitted the project to `lsp-mode`. If `doom-emacs` upgraded `lsp-mode`,there is no need to configure `lsp-volar` separately. Similarly, you can confirm througn `lsp-install-server`.

I did what you wrote here . and it worked like my comment above.

**Comment by jadestrong** [comment]
> * errors in templates about props shows but there not good auto complete for them

https://github.com/jadestrong/lsp-volar#hacks  there is a bug in volar, to make it work, you need to add this code.

> * how to allow autocomplete for components in node_modules ?

Make sure `lsp-typescript-suggest-auto-imports` variable is `t` .

> * how to make lsp + company faster when writing vue code ?

At present, the experience of LSP in Emacs can not achieve the effect of vscode, so we can only improve it as much as possible. For example, use **Emacs 28 natively compiled version** and to ensure that the JSON library implemented in C language is available (try `C-x C-e`  this code `(fboundp 'json-serialize)` , expected output `t`).
In addition, to ensure the latest version of **volar**, ` M-x lsp-update-server`, first you need to update the `lsp-mode` dependency of doom. Currently doom is locked in a previous version. You need to add ` (unpin! lsp-mode)' in `.doom.d/packages.el` .

**Comment by noor-tg** [comment]
> https://github.com/jadestrong/lsp-volar#hacks there is a bug in volar, to make it work, you need to add this code.

- I added the hack . and it is working :like:


> Emacs 28 natively compiled version

I updated it like you said .

> (fboundp 'json-serialize)

it is true

> (unpin! lsp-mode)
updated to latest lsp mode with this

> Make sure lsp-typescript-suggest-auto-imports variable is t .

it is set to true. but the auto import is not working yet.
do I need ts-ls to be running ? or volar will use it under the hood ?
when I run `lsp-describe-session`  I see only volar (api, html, doc) + tailwindcss servers running and associated with the current file.


thank you.

**Comment by noor-tg** [comment]
when try to complete mdiPen to mdiPencil in `ts` files it is slow but working . and auto import after select the term from company list.
but in vue  files with `volar` is not working

**Comment by jadestrong** [comment]
The underlying layer of **volar** calls typescript by itself. You don't need to config `ts-ls` alone.
The performance experience under Emacs is really not very good. If your project is large, the experience will be even worse.

**Comment by jadestrong** [comment]
https://github.com/johnsoncodehk/volar-starter 
You can try whether autoimport is normal in this project. This project is relatively light.

**Comment by noor-tg** [comment]
> The underlying layer of volar calls typescript by itself. You don't need to config ts-ls alone.

ok

> https://github.com/johnsoncodehk/volar-starter
> You can try whether autoimport is normal in this project. This project is relatively light.

I will test the external packages there.

thank you.

**Comment by noor-tg** [comment]
after some tests. the autocomplete & import is working in vue files in script block (very slow i.e need like 10s to load icons list) .

but it is not working in the template section.

any way thank you.

**Comment by jadestrong** [comment]
> but it is not working in the template section.

https://github.com/jadestrong/lsp-volar#hacks  Did you add this advice?  In my case ,after adding this, I can work in the template.

**Comment by nour-dev** [comment]
> 

yes I did.

**Comment by noor-tg** [comment]
> > but it is not working in the template section.
> 
> https://github.com/jadestrong/lsp-volar#hacks Did you add this advice? In my case ,after adding this, I can work in the template.


yes I did.

**Comment by jadestrong** [comment]
Is there any errors or warnings thrown? If not, make sure there is no `(warning-suppress-log-types '((lsp-mode)))`  in `.doom.d/custom.el` .

Or `M-x lsp-toggle-trace-io` ,  open the `*lsp-load: volar-api*` buffer and see the `textDocument/completion` request and response inside.

**Comment by nour-dev** [comment]
hey, again.
in `volar-api::stderr` there is line like
```bash
load volar.config.js failed in /path/to/project
```
is `volar.config.js` required for volar to function correctly with vue/vite project ?

**Comment by noor-tg** [comment]
> Is there any errors or warnings thrown? If not, make sure there is no `(warning-suppress-log-types '((lsp-mode)))` in `.doom.d/custom.el` .

in volar-api::stderr there is line like
```
load volar.config.js failed in /path/to/project
```

is volar.config.js required for volar to function correctly with vue/vite project ?

**Comment by jadestrong** [comment]
This can be ignored. It will also be reported in vscode. This is a new addition to volar to configure some plugins. It is generally not required in normal operation.
