### ISSUE TITLE
Disable document.getDocumentVersionRequest

### ISSUE THREAD

**Issue by ghost** [jadestrong/lsp-volar#5]
I think volar uses its own method that doesn't align with the spec - it's `vue/docVersion`. This results in stuff like this:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/5359825/160382446-e7354fe8-1356-47fd-a031-fbb2f781c7af.png">

I actually had the exact same problem in my custom volar lsp config in neovim, and I solved it by disabling getting the doc version: https://github.com/sethidden/dotfiles/commit/502a1437cb31c919cd0ee44933fcf6f107c1e4a0#diff-23e3c33e20e88165b0a3ff0e996bd3347b820b0b36731dab1a04a4f9cbc3373aR185

By the way: now that lsp-volar is merged into lsp-mode, do you know it it's possible to get the latest commit of lsp-mode in doom? I see that lsp-mode has 2 releases per year which is a really long wait. Was wondering if it's possible to get it earlier

**Comment by jadestrong** [comment]
Try add `(unpin! lsp-mode)` to `~/.doom.d/packages.el`
