### ISSUE TITLE
[Question] Any reason starting 3 volar servers?

### ISSUE THREAD

**Issue by sdvcrx** [jadestrong/lsp-volar#8]
The memory usage of `volar` is extremely high (1G+ RAM). `lsp-volar` start 3 volar servers ( `volar-api`, `volar-html`, `volar-doc` ) in a project, Eventually it take 3G+ RAM in a project.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/5170232/186626516-9c4f5236-e0a7-471a-9467-d12f34e74da9.png">

**Comment by jadestrong** [comment]
Sorry for the late reply. The reason for splitting into three is that the volar is too slow. The volar vscode plugin was originally implemented in this way. Now it seems to be changed into two. I will change it when I have time

**Comment by sdvcrx** [comment]
Thanks for your explanation! I merged three servers into one and the performance is acceptable for me.
