### ISSUE TITLE
Volar is adding 3 language servers

### ISSUE THREAD

**Issue by JoshTRN** [jadestrong/lsp-volar#9]
Hi. I'm using spacemacs and for some reason when LSP starts in vue-mode it adds 3 language servers. Those are:

(server-id volar-api, priority 0), (server-id eslint, priority -1), (server-id volar-doc, priority 0), (server-id volar-html, priority 0)

You can see all three in this screenshot:
![image](https://user-images.githubusercontent.com/33141876/204101144-be9db2ca-cce3-4caa-9940-82fe2bb94836.png)

This makes things like doc help and go to definition show the same thing three times. Here's an example:

![image](https://user-images.githubusercontent.com/33141876/204101205-51649b4c-ef4a-40a8-bd4d-8faeedcb0ef5.png)

![image](https://user-images.githubusercontent.com/33141876/204101283-3b41011a-af18-44ad-9262-2da113b5b3a1.png)

And also it adds wherever I'm at in the file 3 times to the header:

![image](https://user-images.githubusercontent.com/33141876/204101229-b6eebb32-e1a6-4965-9afc-b21f68350fe7.png)

This is unexpected behavior. Is there a work around so that it's only using, say, volar-api given that they all seem to have the same functionality?

**Comment by jadestrong** [comment]
You don't need this package anymore, this repo has already been merged into `lsp-mode` repo, so you can remove `lsp-volar` 's config from your config file.
And then you must upgrade `lsp-mode` to the latest version, upgrade `@volar/vue-language-server` to the latest version, then it will only start one server `vue-semantic-server`.
Then the header maybe can works well, as the header not a lsp-mode' function.

**Comment by JoshTRN** [comment]
Thank you. I had to update my packages. That was the issue.

**Comment by JoshTRN** [comment]
I did have some issues with it. I put the issue on the [lsp-mode repo](https://github.com/emacs-lsp/lsp-mode/issues/3830) but I thought it might be useful to let you know of it here:
